config/routes.rb
Rails.application.routes.draw do 

  root 'posts#index'
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

   def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
     respond_to do |format|
       format.html {redirect_to @post}
       format.js
     end
  end
 end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @posts }
      format.json { render :json => @posts }
      format.atom{ headers["Content-Type"] = 'application/atom+xml; charset=utf-8'}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p>
<strong>Posted <%= time_ago_in_words(comment.created_at) %>
ago</strong><br/>
<%= h(comment.body) %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>
<%= render :partial => @comments %>
<%= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= auto_discovery_link_tag :atom, posts_path(:format => :atom) %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/header"%>
<div class="content-container">
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>
<center>
<h2><%= link_to_unless_current h(post.title), post %></h2>
</center>
<%= simple_format h(post.body) %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="pull-right">
  <%= link_to image_tag("welcome.jpg",:width => "200",:height => "150"), new_post_path %>
</div>

<% @posts.each do |post| %>
<%= render :partial => post %>
<%= render :partial => post.comments %>
<div class="pull-right">
 <%= form_for [post, Comment.new] do |f| %>
    <p>
    <br/>
    <%= f.text_area :body %>
    </p>
    <p><%= f.submit "Add Comment",:class => "btn btn-warning"%></p>
  <% end %>
</div>
<br>

<% end %>

app/views/posts/new.html.erb
<h4>New post</h4>

<%= render 'form' %>
<div class="pull-right">

<%= link_to image_tag("backk.png", :width => "40px", :height => "10px"), posts_path %>
</div>

app/views/posts/show.html.erb
<div class="pull-right">

<p>
<%= link_to 'Edit', edit_post_path(@post),:class => "label label-warning" %> |
<%= link_to 'Delete', @post, :method => :delete, :confirm => "Are you sure?",:class => "label label-warning" %>
</p>
</div>
<%= render :partial => @post %>

<h5>Comments</h5>
<div id="comments">
<%= render :partial => @post.comments %>
</div>
<% form_for [@post, Comment.new], :remote => true do |f| %>
<p>
<%= f.label :body, "new comment" %><br/>
<%= f.text_area :body %>
</p>
<p><%= f.submit "Add Comment" %></p>
<% end %>

<div class="pull-right">

<%= link_to image_tag("backk.png", :width => "40px", :height => "10px"), posts_path %>
</div>

app/views/shared/_footer.html.haml
.container2
  .pull-right.text-muted
    = raw("<i class = 'glyphicon glyphicon-copyright-mark'></i>#{link_to 'OstryaLabs.', 'http://www.ostryalabs.com', :class =>"text-muted"} All Rights Reserved")
    = link_to image_tag("img8.jpeg", :height => "24px", :width => "30px"), "#"
    = link_to image_tag("img9.jpeg", :height => "24px", :width => "30px"), "#"
    = link_to image_tag("img10.jpeg", :height => "24px", :width => "30px"), "#"
      

app/views/shared/_header.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      .container
        .three
          .row
            .col-sm-10  
              %center MY BLOG
              